### ISSUE TITLE
Allow for NFC normalization in output

### ISSUE THREAD

**Issue by LinguList** [bambooforest/segments#2]
I can easily write a wrapper to have NFC normalization in output, as this is useful for my purposes, and LingPy uses NFC, but I suggest it would not be difficult to already include this in the tokenizer itself, that is, when initializing the instance, one could just pass a keyword specifying normalization, or one could allow for a keyword in the output of t.transform. Or would you prefer me to handle it from my side?

**Comment by xrotwang** [comment]
See https://github.com/bambooforest/segments/blob/fdb6b7ef98b8e013139c61334d6b53f6aa0920a7/segments/tokenizer.py#L161

**Comment by LinguList** [comment]
cool, thanks a lot!

**Comment by bambooforest** [comment]
Looks like this will be:

NFC, NFKC, NFD, and NFKD

as per Python unicodedata

**Comment by xrotwang** [comment]
Yeah, that should probably checked, i.e.:
```python
assert form is None or form in ['NFC', 'NFKC', ...]
```

**Comment by bambooforest** [comment]
ok, i'll write a test
